export const admin = {
  ar: {
    title: "لوحة الإدارة",
    tabs: { users: "العملاء", guarantors: "طلبات الكفيل الرقمي", loans: "طلبات التمويل" },
    common: {
      saveFailed: "فشل حفظ القرار", updateUserFailed: "تعذر تحديث حالة المستخدم. يرجى المحاولة مرة أخرى.",
      tryAgain: "يرجى المحاولة مرة أخرى.", requiredReason: "السبب مطلوب", explainRevision: "يرجى توضيح سبب تعديل القرار.",
      cancel: "إلغاء", confirmReject: "تأكيد الرفض", confirmRevision: "تأكيد التعديل", rejectionReason: "سبب الرفض",
      revisionReason: "سبب التعديل", newStatus: "الحالة الجديدة", approve: "قبول", reject: "رفض",
      details: "التفاصيل", unavailable: "غير متوفر", status: "الحالة", name: "الاسم", updated: "آخر تحديث",
      debtRatio: "نسبة عبء الدين", stacking: "تكديس ديون", noUsers: "لا يوجد مستخدمين مسجلين بعد.",
      loadingUsersError: "حدث خطأ أثناء تحميل بيانات المستخدمين.", loadingCustomerError: "حدث خطأ أثناء تحميل بيانات العميل.",
      emptyHistory: "لا يوجد سجل محفوظ لهذا القرار.", reason: "السبب", admin: "المسؤول",
      approveStatus: "مقبول - موثّق", rejectedStatus: "مرفوض", pendingStatus: "قيد المراجعة", incompleteStatus: "غير مكتمل",
    },
    users: { total: "إجمالي المستخدمين: {{count}}", rejectionDescription: "سيظهر هذا السبب للعميل حتى يتمكن من تصحيح بياناته وإعادة التقديم.", rejectionPlaceholder: "مثال: صورة الهوية غير واضحة، يرجى رفع صورة أوضح" },
    detail: {
      title: "تفاصيل العميل", identityPhotos: "صور التحقق من الهوية", idFront: "الهوية - الوجه الأمامي", idBack: "الهوية - الوجه الخلفي", selfie: "الصورة الشخصية (السيلفي)",
      typedName: "الاسم المُدخل", extractedName: "الاسم المستخرج من الهوية", typedNationalId: "الرقم الوطني المُدخل", extractedNationalId: "الرقم الوطني المستخرج", faceMatch: "تطابق الوجه", confidence: "درجة الثقة",
      financial: "الملف المالي", income: "الدخل الشهري", employment: "حالة التوظيف", employer: "جهة العمل", statementsCount: "عدد الكشوفات", dataSource: "مصدر البيانات", verified: "موثّق من كشوفات", selfReported: "مُصرَّح ذاتياً",
      accounts: "الحسابات البنكية", selfDebts: "الديون المُصرَّح بها ذاتياً", statements: "الكشوفات المرفوعة", remaining: "متبقي", rejection: "سبب الرفض", missingImage: "لا توجد صورة",
    },
    guarantors: {
      insightFailed: "تعذر توليد التحليل", decisionFailed: "تعذر حفظ القرار", revisionFailed: "تعذر تعديل قرار الكفالة", revisionExpired: "قد تكون فترة التعديل المسموح بها قد انتهت، أو تغيّرت حالة الطلب. يرجى تحديث الصفحة والمحاولة مرة أخرى.",
      loadError: "حدث خطأ أثناء تحميل طلبات الكفالة.", awaiting: "بانتظار المراجعة: {{count}}", requestsFrom: "يطلب كفالة من", applicant: "مقدّم الطلب", guarantor: "الكفيل", currentlyGuarantees: "يكفل حالياً {{active}} / {{max}}", maxAmount: "الحد الأقصى للكفالة", aiAnalysis: "تحليل الذكاء الاصطناعي", recommendation: "توصية", approveRecommendation: "موافقة", rejectRecommendation: "رفض", aiButton: "تحليل بالذكاء الاصطناعي", approveGuarantee: "الموافقة على الكفالة", rejectGuarantee: "رفض الكفالة", edit: "تعديل القرار", hideHistory: "إخفاء سجل القرارات", showHistory: "عرض سجل القرارات", history: "سجل قرارات الإدارة", noRequests: "لا يوجد طلبات كفالة رقمية حتى الآن.", fromTo: "من {{from}} إلى {{to}}", revisionTitle: "تعديل قرار الكفالة الرقمية", revisionDescription: "يُستخدم هذا لتصحيح قرار حديث اتُّخذ بالخطأ أو بناءً على معلومات غير محدّثة. سيتم إشعار مقدّم الطلب والكفيل بالتعديل، ولا يمكن تعديل قرار مرّت عليه أكثر من ١٤ يومًا.", approved: "الموافقة", rejected: "الرفض", revisionPlaceholder: "مثال: تم اتخاذ القرار بناءً على معلومات غير محدّثة.",
      riskLow: "منخفض", riskMedium: "متوسط",
      awaitingStatus: "بانتظار قرار الإدارة", approvedStatus: "موافق عليه", rejectedStatus: "مرفوض",
    },
    loans: {
      approvedStatus: "تمت الموافقة", rejectedStatus: "مرفوض", awaitingStatus: "بانتظار القرار النهائي", finalApproval: "موافقة نهائية", returnReview: "إعادة للمراجعة", loadError: "حدث خطأ أثناء تحميل طلبات التمويل.", awaiting: "بانتظار القرار النهائي: {{count}}", requested: "المبلغ المطلوب", recommended: "المبلغ الموصى به", score: "الدرجة الائتمانية", risk: "مستوى المخاطرة", purpose: "الغرض", guaranteed: "مدعوم بكفيل رقمي مُوافَق عليه (معرّف الكفالة: {{id}})", rejection: "سبب الرفض", history: "سجل قرارات الإدارة", export: "تصدير السجل", firstDecision: "القرار الأول", edit: "تعديل القرار", approve: "الموافقة النهائية", reject: "رفض الطلب", noApplications: "لا يوجد طلبات تمويل تنتظر القرار النهائي بعد.", rejectionDescription: "سيظهر هذا السبب للعميل ضمن حالة طلبه.", rejectionPlaceholder: "مثال: عدم استقرار الدخل خلال الأشهر الأخيرة", revisionTitle: "تعديل القرار النهائي", revisionDescription: "يُستخدم هذا لتصحيح قرار حديث اتُّخذ بالخطأ أو بناءً على معلومات غير محدّثة. سيتم إشعار العميل (والكفيل إن وُجد) بالتعديل، ولا يمكن تعديل قرار مرّت عليه أكثر من ١٤ يومًا.", returnSubmitted: "إعادة الطلب لبانتظار القرار النهائي", revisionPlaceholder: "مثال: تمت الموافقة بالخطأ على طلب آخر، هذا القرار يصحّحه.",
    },
  },
  en: {
    title: "Admin Panel", tabs: { users: "Customers", guarantors: "Digital Guarantor Requests", loans: "Financing Requests" },
    common: { saveFailed: "Failed to save decision", updateUserFailed: "Unable to update the user status. Please try again.", tryAgain: "Please try again.", requiredReason: "Reason required", explainRevision: "Please explain why the decision is being revised.", cancel: "Cancel", confirmReject: "Confirm rejection", confirmRevision: "Confirm revision", rejectionReason: "Rejection reason", revisionReason: "Revision reason", newStatus: "New status", approve: "Approve", reject: "Reject", details: "Details", unavailable: "Unavailable", status: "Status", name: "Name", updated: "Last updated", debtRatio: "Debt-to-income ratio", stacking: "Debt stacking", noUsers: "No registered users yet.", loadingUsersError: "An error occurred while loading user data.", loadingCustomerError: "An error occurred while loading customer data.", emptyHistory: "No history is saved for this decision.", reason: "Reason", admin: "Admin", approveStatus: "Approved - Verified", rejectedStatus: "Rejected", pendingStatus: "Under review", incompleteStatus: "Incomplete" },
    users: { total: "Total users: {{count}}", rejectionDescription: "The customer will see this reason and can correct their information before reapplying.", rejectionPlaceholder: "Example: The ID image is unclear; please upload a clearer image" },
    detail: { title: "Customer details", identityPhotos: "Identity verification photos", idFront: "ID - Front", idBack: "ID - Back", selfie: "Selfie", typedName: "Entered name", extractedName: "Name extracted from ID", typedNationalId: "Entered national ID", extractedNationalId: "National ID extracted from ID", faceMatch: "Face match", confidence: "Confidence score", financial: "Financial profile", income: "Monthly income", employment: "Employment status", employer: "Employer", statementsCount: "Statement count", dataSource: "Data source", verified: "Verified from statements", selfReported: "Self-reported", accounts: "Bank accounts", selfDebts: "Self-reported debts", statements: "Uploaded statements", remaining: "remaining", rejection: "Rejection reason", missingImage: "No image" },
    guarantors: { insightFailed: "Unable to generate analysis", decisionFailed: "Unable to save decision", revisionFailed: "Unable to revise guarantor decision", revisionExpired: "The revision window may have expired or the request status may have changed. Refresh and try again.", loadError: "An error occurred while loading guarantor requests.", awaiting: "Awaiting review: {{count}}", requestsFrom: "requests a guarantee from", applicant: "Applicant", guarantor: "Guarantor", currentlyGuarantees: "Currently guarantees {{active}} / {{max}}", maxAmount: "Maximum guarantee", aiAnalysis: "AI analysis", recommendation: "Recommendation", approveRecommendation: "Approve", rejectRecommendation: "Reject", aiButton: "Analyze with AI", approveGuarantee: "Approve guarantee", rejectGuarantee: "Reject guarantee", edit: "Revise decision", hideHistory: "Hide decision history", showHistory: "Show decision history", history: "Admin decision history", noRequests: "No digital guarantor requests yet.", fromTo: "From {{from}} to {{to}}", revisionTitle: "Revise digital guarantee decision", revisionDescription: "Use this to correct a recent decision made in error or using outdated information. The applicant and guarantor will be notified; decisions older than 14 days cannot be revised.", approved: "Approve", rejected: "Reject", revisionPlaceholder: "Example: The decision was based on outdated information.", riskLow: "Low", riskMedium: "Medium", awaitingStatus: "Awaiting admin decision", approvedStatus: "Approved", rejectedStatus: "Rejected" },
    loans: { approvedStatus: "Approved", rejectedStatus: "Rejected", awaitingStatus: "Awaiting final decision", finalApproval: "Final approval", returnReview: "Return for review", loadError: "An error occurred while loading financing requests.", awaiting: "Awaiting final decision: {{count}}", requested: "Requested amount", recommended: "Recommended amount", score: "Credit score", risk: "Risk level", purpose: "Purpose", guaranteed: "Backed by an approved digital guarantor (guarantee ID: {{id}})", rejection: "Rejection reason", history: "Admin decision history", export: "Export history", firstDecision: "Initial decision", edit: "Revise decision", approve: "Final approval", reject: "Reject request", noApplications: "No financing requests are awaiting a final decision.", rejectionDescription: "The customer will see this reason with their application status.", rejectionPlaceholder: "Example: Income has been unstable in recent months", revisionTitle: "Revise final decision", revisionDescription: "Use this to correct a recent decision made in error or using outdated information. The customer (and guarantor, if any) will be notified; decisions older than 14 days cannot be revised.", returnSubmitted: "Return application to awaiting final decision", revisionPlaceholder: "Example: Another application was approved by mistake; this revision corrects it." },
  },
};