export const dashboard = {
  ar: {
    review: { pending: "جاري مراجعة ملفك", pendingBody: "يقوم خبراؤنا بمراجعة مستنداتك وبياناتك المالية. هذه العملية تستغرق وقتاً قصيراً لضمان تقديم أفضل الاستشارات المخصصة لك.", rejected: "تم رفض الملف", defaultReason: "المستندات غير مطابقة للشروط", resubmit: "إعادة التقديم" },
    error: { financial: "حدث خطأ أثناء تحميل بياناتك المالية.", generic: "حدث خطأ", submit: "حدث خطأ أثناء إرسال الطلب، الرجاء المحاولة مرة أخرى.", guarantor: "لم نتمكن من العثور على هذا الشخص أو أنه غير مؤهل ليكون كفيلاً رقمياً.", retry: "يرجى المحاولة مرة أخرى." },
    welcome: { greeting: "أهلاً بك، {{name}}", customer: "عميلنا العزيز", verified: "حساب موثّق", summary: "إليك ملخص وضعك المالي بناءً على البيانات المقدمة.", debtTotal: "إجمالي الديون المتبقية", unverified: "الأرقام أدناه مبنية على بياناتك المُدخلة عند التسجيل فقط. ستظهر أرقام دقيقة بعد رفع كشوفات حساباتك أو قروضك ومراجعتها." },
    kpi: { income: "الدخل الشهري", payments: "الالتزامات الشهرية", ratio: "نسبة عبء الدين", loans: "عدد القروض النشطة" },
    services: { heading: "الخدمات الاستشارية المتاحة لك", analysis: { title: "تحليل شامل للبيانات", description: "دراسة مفصلة لوضعك المالي وتوزيع ديونك عبر الجهات المختلفة." }, advice: { title: "نصائح الذكاء الاصطناعي", description: "نصائح مالية مخصصة مبنية على خوارزمياتنا لتحسين تصنيفك الائتماني." }, restructure: { title: "خطط إعادة الهيكلة", description: "سيناريوهات مقترحة لتقليل القسط الشهري وتقليص فترة السداد." }, consolidation: { title: "طلب توحيد القروض", description: "جمع كافة ديونك من المؤسسات المختلفة في قرض واحد بقسط مريح." }, eligibility: { title: "تقييم أهلية التمويل", description: "فحص سريع لمدى أهليتك للحصول على تمويل إضافي دون الإضرار بوضعك المالي." } },
    application: { ready: "جاهز لتمويل جديد؟", readyBody: "قدّم طلبك الآن وسنقيّم أهليتك فوراً، وإذا احتجت كفيلاً رقمياً نساعدك تطلبه من نفس المكان.", new: "طلب تمويل جديد", latest: "طلب التمويل الأخير", requested: "المبلغ المطلوب", purpose: "الغرض", recommended: "المبلغ الموصى به", installment: "القسط الشهري", newRequest: "تقديم طلب جديد", reason: "سبب الرفض", guarantorNote: "أغلق هذه النافذة وستجد في بطاقة \"طلب التمويل الأخير\" خياراً لطلب كفيل رقمي يدعم طلبك.", close: "إغلاق", amountLabel: "المبلغ المطلوب ({{currency}})", amountPlaceholder: "مثال: 1000", purposeLabel: "الغرض من التمويل", purposePlaceholder: "مثال: تجديد المنزل، شراء سيارة، توسيع مشروعي الخاص...", send: "إرسال الطلب" },
    status: { submitted: "تم الإرسال، قيد المراجعة النهائية", awaiting: "بانتظار كفيل رقمي", approved: "تمت الموافقة النهائية", adminRejected: "رُفض بعد المراجعة النهائية", rejected: "غير مؤهل حالياً" },
    guarantor: { requestSent: "تم إرسال الطلب", requestSentTo: "تم إرسال طلب الكفالة إلى {{name}}.", requestFailed: "تعذر إرسال الطلب", nationalId: "الرقم الوطني للكفيل", request: "طلب كفيل", digital: "الكفيل الرقمي", intro: "اطلب من عميل موثّق أن يكفلك، أو راجع طلبات الكفالة الواردة إليك", applicationNeed: "طلبك يحتاج كفيلاً رقمياً لإتمام الموافقة. أدخل الرقم الوطني لشخص موثّق عندنا ليكون كفيلك.", yourGuarantors: "كفلاؤك", guaranteed: "من تكفلهم أنت", max: "حتى {{amount}} {{currency}}", incoming: "طلبات كفالة واردة إليك", maxAmount: "بحد أقصى {{amount}} {{currency}}", newRequest: "طلب كفيل رقمي جديد", active: "نشطة ({{count}})", pending: "قيد الانتظار ({{count}})", closed: "مرفوضة/منتهية ({{count}})", empty: "لا توجد سجلات في هذه الفئة", yourGuarantor: "كفيلك", youGuarantee: "تكفله أنت", responseFailed: "تعذر تسجيل الرد" },
    dialogs: { analysis: "التحليل الشامل", advice: "استشارة الذكاء الاصطناعي", restructure: "خطة إعادة الهيكلة المقترحة", consolidation: "طلب توحيد القروض", eligibility: "تقييم أهلية التمويل الإضافي", awaiting: "بياناتك المالية لا تزال قيد المراجعة والتحليل من قبل فريقنا. سنعلمك فور اكتمال التحليل لعرض نتائجك الدقيقة.", debtTotal: "إجمالي الدين المتبقي", burden: "نسبة العبء", breakdown: "تفصيل الديون", insights: "رؤى مالية", current: "العبء الحالي", target: "العبء المستهدف", duration: "المدة المتوقعة لتنفيذ الخطة: {{months}} أشهر", initialSuccess: "تم تسجيل طلبك المبدئي", requestNumber: "رقم الطلب: #{{id}}", institutions: "المؤسسات المشمولة:", estimated: "القسط الموحد التقديري:", contact: "سيقوم أحد مستشارينا بالتواصل معك قريباً لاستكمال الإجراءات.", creditScore: "درجتك الائتمانية", eligible: "أنت مؤهل للحصول على تمويل إضافي", notEligible: "غير مؤهل حالياً لتمويل إضافي", expectedInstallment: "القسط الشهري المتوقع" },
  },
  en: {
    review: { pending: "Your profile is under review", pendingBody: "Our experts are reviewing your documents and financial information. This takes a short time so we can provide the best advice tailored to you.", rejected: "Profile rejected", defaultReason: "The documents do not meet the requirements", resubmit: "Submit again" },
    error: { financial: "An error occurred while loading your financial data.", generic: "An error occurred", submit: "An error occurred while submitting the application. Please try again.", guarantor: "We could not find this person or they are not eligible to be a digital guarantor.", retry: "Please try again." },
    welcome: { greeting: "Welcome, {{name}}", customer: "valued customer", verified: "Verified account", summary: "Here is a summary of your financial position based on the information provided.", debtTotal: "Total remaining debt", unverified: "The figures below are based only on the information entered during registration. Accurate figures will appear after your account or loan statements are uploaded and reviewed." },
    kpi: { income: "Monthly income", payments: "Monthly obligations", ratio: "Debt burden ratio", loans: "Active loans" },
    services: { heading: "Advisory services available to you", analysis: { title: "Comprehensive data analysis", description: "A detailed study of your finances and debt distribution across institutions." }, advice: { title: "AI-powered advice", description: "Personalized financial advice based on our algorithms to improve your credit standing." }, restructure: { title: "Restructuring plans", description: "Suggested scenarios to reduce your monthly installment and shorten your repayment period." }, consolidation: { title: "Loan consolidation request", description: "Combine all your debts from different institutions into one loan with a comfortable installment." }, eligibility: { title: "Financing eligibility check", description: "A quick check of your eligibility for additional financing without harming your financial position." } },
    application: { ready: "Ready for new financing?", readyBody: "Apply now and we will assess your eligibility immediately. If you need a digital guarantor, you can request one here.", new: "New financing request", latest: "Latest financing request", requested: "Requested amount", purpose: "Purpose", recommended: "Recommended amount", installment: "Monthly installment", newRequest: "Submit a new request", reason: "Rejection reason", guarantorNote: "Close this window to find an option in the Latest Financing Request card to request a digital guarantor for your application.", close: "Close", amountLabel: "Requested amount ({{currency}})", amountPlaceholder: "Example: 1,000", purposeLabel: "Financing purpose", purposePlaceholder: "Example: home renovation, buying a car, expanding my business...", send: "Submit request" },
    status: { submitted: "Submitted, under final review", awaiting: "Awaiting digital guarantor", approved: "Final approval granted", adminRejected: "Rejected after final review", rejected: "Currently ineligible" },
    guarantor: { requestSent: "Request sent", requestSentTo: "The guarantor request was sent to {{name}}.", requestFailed: "Unable to send request", nationalId: "Guarantor national ID", request: "Request guarantor", digital: "Digital guarantor", intro: "Ask a verified customer to guarantee you, or review incoming guarantor requests.", applicationNeed: "Your application needs a digital guarantor to complete approval. Enter the national ID of a verified person to guarantee you.", yourGuarantors: "Your guarantors", guaranteed: "People you guarantee", max: "up to {{amount}} {{currency}}", incoming: "Incoming guarantor requests", maxAmount: "up to {{amount}} {{currency}}", newRequest: "Request a new digital guarantor", active: "Active ({{count}})", pending: "Pending ({{count}})", closed: "Declined/closed ({{count}})", empty: "No records in this category", yourGuarantor: "Your guarantor", youGuarantee: "You guarantee", responseFailed: "Unable to record response" },
    dialogs: { analysis: "Comprehensive analysis", advice: "AI advice", restructure: "Proposed restructuring plan", consolidation: "Loan consolidation request", eligibility: "Additional financing eligibility", awaiting: "Your financial data is still being reviewed and analyzed by our team. We will notify you when the analysis is complete.", debtTotal: "Total remaining debt", burden: "Debt burden", breakdown: "Debt breakdown", insights: "Financial insights", current: "Current burden", target: "Target burden", duration: "Expected plan duration: {{months}} months", initialSuccess: "Your preliminary request has been recorded", requestNumber: "Request number: #{{id}}", institutions: "Included institutions:", estimated: "Estimated consolidated installment:", contact: "One of our advisors will contact you shortly to complete the process.", creditScore: "Your credit score", eligible: "You are eligible for additional financing", notEligible: "You are currently not eligible for additional financing", expectedInstallment: "Expected monthly installment" },
  },
};