"""
Persistence for loan-consolidation requests.

Consolidation requests are recorded in the shared `consolidation_requests`
Postgres table (schema owned by `lib/db/src/schema/consolidationRequests.ts`,
also written to by the legacy TypeScript API server in
`artifacts/api-server/src/routes/finance.ts`). Persisting here -- instead of
handing back an in-memory/fabricated id -- means a submitted request is a
real, durable record an admin can later look up, not just a number the
customer sees once in the dialog.
"""

import logging
import os
from datetime import datetime

import psycopg2
import psycopg2.extras

logger = logging.getLogger("debtlens")


def _database_url() -> str:
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL must be set. Did you forget to provision a database?")
    return url


def insert_consolidation_request(
    uid: str,
    institutions_included: int,
    estimated_consolidated_monthly_payment: float,
) -> dict:
    """
    Insert a new consolidation request row and return the persisted
    {id, status, createdAt} generated by the database (id sequence,
    default status, default timestamp) -- never fabricated in Python.
    """
    with psycopg2.connect(_database_url()) as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                """
                INSERT INTO consolidation_requests
                    (uid, institutions_included, estimated_consolidated_monthly_payment)
                VALUES (%s, %s, %s)
                RETURNING id, status, created_at
                """,
                (uid, institutions_included, estimated_consolidated_monthly_payment),
            )
            row = cur.fetchone()
        conn.commit()

    created_at: datetime = row["created_at"]
    return {
        "id": row["id"],
        "status": row["status"],
        "createdAt": created_at.isoformat(),
    }
